### ISSUE TITLE
Can't keep up! Is the server overloaded?

### ISSUE THREAD

**Issue by teracube** [matcracker/BedcoreProtect#32]
### Issue description
high consumption of CPU and RAM using BedcoreProtect on my server

tested on a server with 40 players connected and 40 plugins
With BedcoreProtect
lag server
CPU at 150%/200% permanently
RAM 6000 MB of 8000 MB

Without BedcoreProtect
CPU at 30%/50%
RAM 700 MB of 8000 MB
no lag

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. ... test a server with and without BedcoreProtect
2. ...compare performance

### OS and versions

* BedcoreProtect:  
https://poggit.pmmp.io/r/88554/BedcoreProtect_dev-318.phar

* PocketMine-MP: 
https://jenkins.pmmp.io/job/PocketMine-MP/1795/artifact/PocketMine-MP.phar
* PHP:
* Server OS: Linux
* Game version: PE/Win10 (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by matcracker** [comment]
Can you share your configuration file?

**Comment by teracube** [comment]
my config file
[config.zip](https://github.com/matcracker/BedcoreProtect/files/4679410/config.zip)

**Comment by matcracker** [comment]
Ok, you are using the default config. I suggest you to change the following keys:
- Increment the number of `worker-limit` to **3**.
- Enable the logs only in the worlds where you actually need.
Example:
```yaml
enabled-worlds:
  - FactionWorld
  - SurvivalWorld
```
The spawn world does not need to be tracked because is useless, so don't add it.
- Choose which types of logs you really need to track, for example: `leaves-decay` and `player-interactions` can be set to `false` because not really useful.

_P.S. I would like to point out that the plugin requires a lot of resources because it has to keep track of everything and unfortunately there is no different way. It is certainly not fully optimized but I will work to do it._

**Comment by matcracker** [comment]
Try the last build available and let me know :)

**Comment by teracube** [comment]
I tried f6c0fb2 with defaut config
MTU set to 1200
50/100 players connected
Average RAM 1600 / 8000 MB =) really better
Average CPU usage 140 % =) better but high (50% without BedCoreProtect)
no message "Can't keep up! Is the server overloaded?"
It's better with this build

thanks
