### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by MrBlasyMSK** [matcracker/BedcoreProtect#65]
Do you plan to continue with this plugin for API 4? I have seen that you have reported 2 crash and I would like to know if it is stable.

**Comment by matcracker** [comment]
Hi, yes the plugin is maintained and stable otherwise it would not be released on poggit. The 2 crashes comes from the PMMP crash archive (no one has ever reported these issues) and I don't know the cause and how to reproduce them. However, if there are ever more details, the problems will be solved.
